### ISSUE TITLE
Implementar CRUD de gastos

### ISSUE THREAD

**Issue by LimaRubson** [Projeto-Engenharia-de-Software-LC/gerenciador_financeiro_pessoal#17]
#9 Desenvolver tela para o usuário cadastrar, visualizar, atualizar e remover gastos

Tutorial de implementação: https://medium.com/@20ce125/django-crud-create-retrieve-update-delete-operations-441a8a296119

O projeto já está criado, onde tem a funcionalidade de cadastrar gastos. O falta é implementar a funcionalidade de visualizar, atualizar e remover. 

Etapas de implementação:
Create the Model
Create the Admin Interface
Create the View
Define the URLs (i.e. URL to View mapping)
Create the Templates

Dupla: Walkiria e Lucas Emmanuel

Divisão da tarefa:

Walkiria: Criar os templates de Atualizar e Remover
Lucas Emmanuel: Criar os models, views e urls

Importante: Por segurança, começar a criar os models, views e urls quando os templates estiverem prontos.

Walkiria deve criar a branch a partir da branch develop. Nome da branch: feature-implementacao-CRUD-de-gastos

**Comment by Dusax** [comment]
Minha parte no requisito foi finalizada na issue #20
