### ISSUE TITLE
App Gastos: Criar os templates de Atualizar e Remover

### ISSUE THREAD

**Issue by LimaRubson** [Projeto-Engenharia-de-Software-LC/gerenciador_financeiro_pessoal#19]
Requisito: #9 

Orientações da execução da tarefa: #17

**Comment by Walquiriawp** [comment]
Foi Feito uma tela de home e delete para gastos. Na views tem funções que implementam as funcionalidades de deletar e atualizar, porém está dando um erro, favor verificar.

**Comment by Walquiriawp** [comment]
Fiz um update no codigo, a funcionalidade de deletar esta funcionando, porém a de atualizar ainda estar dando erro, favor verificar
