### ISSUE TITLE
App Gastos: Criar os models, views e urls

### ISSUE THREAD

**Issue by LimaRubson** [Projeto-Engenharia-de-Software-LC/gerenciador_financeiro_pessoal#20]
Requisito: #9 

Orientações da execução da tarefa: #17

**Comment by Dusax** [comment]
Criado os models, views e urls para o Update e o Delete dos gastos no site.

Testei aqui, e está funcionando normalmente.

as alterações foram enviadas na branch feature-implementacao-CRUD-de-gastos, e após a análise final e aceitação, finalizaremos o requisito #17.
