### ISSUE TITLE
Documentação simples da Microarquitetura e Macroarquitetura

### ISSUE THREAD

**Issue by LimaRubson** [Projeto-Engenharia-de-Software-LC/gerenciador_financeiro_pessoal#27]
- Documentação simples da Microarquitetura, com descrição completa de classes básicas (models) usados no back-end da aplicação
- Documentação simples da Macroarquitetura, com descrição completa dos componentes do sistema e da relação entre eles

**Comment by SrHenrique1002** [comment]
Documentação simples da Microarquitetura iniciada. Disponível para acesso em
[https://ufrpebr-my.sharepoint.com/:w:/g/personal/lucas_hlsilva_ufrpe_br/EZwKAgMLYZhNodABFfR5Ux8B6Jeb0svnjlHQ0k-BoXAUbw?e=rje2O4](url)

Faltam:
-> Diagrama de classes;
-> Descrição dos testes

**Comment by SrHenrique1002** [comment]
Atualização do documento, que engloba a descrição da Microarquitetura e da Macroarquitetura.

Faltam:
-> Diagrama de classes;
-> Descrição dos testes

**Comment by SrHenrique1002** [comment]
@LimaRubson , se possível, edita a parte da descrição dos testes, ou então atribuir a alguma pessoa específica. 

- [ ] Descrição dos testes

**Comment by SrHenrique1002** [comment]
documentação simples da Macro e Microarquitetura concluída
