### ISSUE TITLE
Implementar funcionalidade de login

### ISSUE THREAD

**Issue by Walquiriawp** [Projeto-Engenharia-de-Software-LC/gerenciador_financeiro_pessoal#31]
Foi implementada a função de login, porém é preciso rever a logica da implementação, pois após o usuario se cadastrar no site, ele é redirecionado para a pagina de login que deve abrir uma seção deste mesmo usuario abrindo outras funcionalidades como a pagina de configurações onde ele pode alterar seus dados, seus gastos e receitas. Atualmente a página configurações esta na pagina inicial, porém ela devera ficar disponivel apenas após o usuario logar.

Baixe e suba suas alterações desta funcionalidade pela branch: feature-implemantacao-login

A página de login atualmente encontra-se com este erro, mesmo com senha e usuario corretos.

![image](https://github.com/Projeto-Engenharia-de-Software-LC/gerenciador_financeiro_pessoal/assets/47044643/ed9c0d52-f802-442b-ab5e-31b7a85e0b0b)

**Comment by Dusax** [comment]
Nova branch criada implementar-funcionalidade-de-login

**Comment by Dusax** [comment]
Funcionalidade de login implementada, já é possível cadastrar usuário e fazer o login normalmente, a autenticação está funcionando.

Se faz a necessária a correção de alguns bugs na hora de cadastrar receitas/gastos e na hora de atualizar os usuários.
Também é necessário a atualização do front end para a parte de quando o usuário está logado.

Nesse commit foi adicionado o app login.
Foi mudado a class usuário nos Models, e passou a se chamar CustomUser
